spring:
  application:
    name: ecommerceutk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/globantdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8585


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
